[project]
name = "valkey-timeseries"
version = "0.1.0"
description = "A Timeseries data type for Valkey"
requires-python=">=3.11,<3.12"
dependencies = [
    "valkey",
    "pytest>=6.0,<7.0",
    "pytest-html",
]
